// app/admin/info/page.tsx

"use client"

import Link from "next/link"
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card"
import { Button } from "@/components/ui/button"

export default function AdminInfoPage() {
  return (
      <div className="max-w-2xl mx-auto p-6 space-y-6">
            {/* Admin Info */}
                  <Card className="shadow-md">
                          <CardHeader>
                                    <CardTitle>ℹ️ Admin Info</CardTitle>
                                              <CardDescription>
                                                          Här hittar du information och kontaktuppgifter för Mushroom Maniacs admin.
                                                                    </CardDescription>
                                                                            </CardHeader>
                                                                                    <CardContent className="space-y-4 text-base leading-relaxed">
                                                                                              <p>
                                                                                                          Detta är den officiella informationssidan för admin. Här publiceras
                                                                                                                      viktiga uppdateringar, riktlinjer och supportvägar.
                                                                                                                                </p>
                                                                                                                                          <div className="space-y-2">
                                                                                                                                                      <p><strong>📧 E-post:</strong> magnus.lulea@proton.me</p>
                                                                                                                                                                  <p><strong>📱 Telefon:</strong> +46 0728502584</p>
                                                                                                                                                                            </div>
                                                                                                                                                                                      <p className="text-sm text-muted-foreground">
                                                                                                                                                                                                  All information här är endast för officiellt bruk och uppdateras löpande av admin.
                                                                                                                                                                                                            </p>
                                                                                                                                                                                                                    </CardContent>
                                                                                                                                                                                                                          </Card>

                                                                                                                                                                                                                                {/* Privacy link */}
                                                                                                                                                                                                                                      <Card className="shadow-md">
                                                                                                                                                                                                                                              <CardHeader>
                                                                                                                                                                                                                                                        <CardTitle>🔒 Privacy Policy</CardTitle>
                                                                                                                                                                                                                                                                  <CardDescription>Så här hanteras din integritet.</CardDescription>
                                                                                                                                                                                                                                                                          </CardHeader>
                                                                                                                                                                                                                                                                                  <CardContent>
                                                                                                                                                                                                                                                                                            <Link href="/admin/info/privacy">
                                                                                                                                                                                                                                                                                                        <Button variant="secondary" className="w-full">Läs mer</Button>
                                                                                                                                                                                                                                                                                                                  </Link>
                                                                                                                                                                                                                                                                                                                          </CardContent>
                                                                                                                                                                                                                                                                                                                                </Card>

                                                                                                                                                                                                                                                                                                                                      {/* License link */}
                                                                                                                                                                                                                                                                                                                                            <Card className="shadow-md">
                                                                                                                                                                                                                                                                                                                                                    <CardHeader>
                                                                                                                                                                                                                                                                                                                                                              <CardTitle>📜 License</CardTitle>
                                                                                                                                                                                                                                                                                                                                                                        <CardDescription>Villkor och rättigheter för Mushroom Maniacs.</CardDescription>
                                                                                                                                                                                                                                                                                                                                                                                </CardHeader>
                                                                                                                                                                                                                                                                                                                                                                                        <CardContent>
                                                                                                                                                                                                                                                                                                                                                                                                  <Link href="/admin/info/license">
                                                                                                                                                                                                                                                                                                                                                                                                              <Button variant="secondary" className="w-full">Läs mer</Button>
                                                                                                                                                                                                                                                                                                                                                                                                                        </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                </CardContent>
                                                                                                                                                                                                                                                                                                                                                                                                                                      </Card>

                                                                                                                                                                                                                                                                                                                                                                                                                                            {/* Policy link */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                  <Card className="shadow-md">
                                                                                                                                                                                                                                                                                                                                                                                                                                                          <CardHeader>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <CardTitle>📑 Policy</CardTitle>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <CardDescription>Regler och riktlinjer för plattformen.</CardDescription>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </CardHeader>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <CardContent>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <Link href="/admin/info/policy">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <Button variant="secondary" className="w-full">Läs mer</Button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </CardContent>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </Card>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
