// Path: app/bauta/[id]/page.tsx
import { notFound } from "next/navigation";
import { bautaProjects } from "@/data/bauta";

type Props = { params: { id: string } };

export function generateStaticParams() {
  return bautaProjects.map((p) => ({ id: String(p.id) }));
  }

  export function generateMetadata({ params }: Props) {
    const project = bautaProjects.find((p) => String(p.id) === params.id);
      return {
          title: project ? `${project.title} – BAUTA Project ${project.id}` : "BAUTA Project",
              description: project?.presentation ?? "BAUTA project details",
                };
                }

                export default function BautaProjectPage({ params }: Props) {
                  const project = bautaProjects.find((p) => String(p.id) === params.id);
                    if (!project) return notFound();

                      return (
                          <div className="min-h-screen bg-white text-slate-900 px-4 py-10">
                                <div className="max-w-3xl mx-auto space-y-8">
                                        <header className="space-y-1">
                                                  <h1 className="text-3xl font-bold">
                                                              {project.title} <span className="text-slate-500">• ID {project.id}</span>
                                                                        </h1>
                                                                                  {(project.units || project.totalCostUSD) && (
                                                                                              <p className="text-sm text-slate-600">
                                                                                                            {project.units ? `${project.units} units` : null}
                                                                                                                          {project.units && project.totalCostUSD ? " • " : ""}
                                                                                                                                        {project.totalCostUSD ? `Total: $${project.totalCostUSD.toLocaleString()}` : null}
                                                                                                                                                    </p>
                                                                                                                                                              )}
                                                                                                                                                                      </header>

                                                                                                                                                                              <section className="space-y-2">
                                                                                                                                                                                        <h2 className="text-xl font-semibold">Presentation</h2>
                                                                                                                                                                                                  <p className="leading-relaxed">{project.presentation}</p>
                                                                                                                                                                                                          </section>

                                                                                                                                                                                                                  <section className="space-y-2">
                                                                                                                                                                                                                            <h2 className="text-xl font-semibold">Purpose</h2>
                                                                                                                                                                                                                                      <p className="leading-relaxed">{project.purpose}</p>
                                                                                                                                                                                                                                              </section>

                                                                                                                                                                                                                                                      {project.effects && (
                                                                                                                                                                                                                                                                <section className="space-y-4">
                                                                                                                                                                                                                                                                            <h2 className="text-xl font-semibold">Projected Effects</h2>

                                                                                                                                                                                                                                                                                        {project.effects.shortTerm && (
                                                                                                                                                                                                                                                                                                      <div>
                                                                                                                                                                                                                                                                                                                      <h3 className="font-medium">Short-term (6 months)</h3>
                                                                                                                                                                                                                                                                                                                                      <ul className="list-disc list-inside text-slate-700 space-y-1">
                                                                                                                                                                                                                                                                                                                                                        {project.effects.shortTerm.map((item: string, i: number) => (
                                                                                                                                                                                                                                                                                                                                                                            <li key={`s-${i}`}>{item}</li>
                                                                                                                                                                                                                                                                                                                                                                                              ))}
                                                                                                                                                                                                                                                                                                                                                                                                              </ul>
                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                        )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                    {project.effects.longTerm && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <h3 className="font-medium">Long-term (5 years)</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <ul className="list-disc list-inside text-slate-700 space-y-1">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {project.effects.longTerm.map((item: string, i: number) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <li key={`l-${i}`}>{item}</li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </ul>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
