// app/church/page.tsx
"use client"


export default function Page() {
  return (
      <div className="min-h-screen bg-gradient-to-br from-blue-50 via-white to-purple-50">

            

                  <main className="container mx-auto max-w-3xl px-4 py-10">
                          <h1 className="text-4xl font-bold mb-6 text-center">Hälso-Kyrkan</h1>

                                  <p className="text-center text-gray-700 mb-8">
                                            En plats för tro, hopp och kärlek.  
                                                      Här kan du bedja, lyssna på musik, dela ditt vittnesbörd, och finna friden med själavård.
                                                              </p>

                                                                      {/* Spotify spellista */}
                                                                              <div className="rounded-xl overflow-hidden border shadow mb-10">
                                                                                        <iframe
                                                                                                    src="https://open.spotify.com/embed/playlist/2ZDEz1pWmohIfFJ6gDA11V"
                                                                                                                width="100%"
                                                                                                                            height="352"
                                                                                                                                        frameBorder="0"
                                                                                                                                                    allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture"
                                                                                                                                                                loading="lazy"
                                                                                                                                                                          />
                                                                                                                                                                                  </div>

                                                                                                                                                                                          {/* Kontakt & Själavård */}
                                                                                                                                                                                                  <section className="mb-10">
                                                                                                                                                                                                            <h2 className="text-2xl font-semibold mb-3 text-center"> Själavård 💌</h2>
                                                                                                                                                                                                                      <p className="text-center text-gray-700 mb-4">
                                                                                                                                                                                                                                  Behöver du själavård eller få förbön?

                                                                                                                                                                                                                                  Kontakta oss via e-post eller chatta med oss.
                                                                                                                                                                                                                                            </p>
                                                                                                                                                                                                                                                      <div className="flex justify-center gap-4">
                                                                                                                                                                                                                                                                  <a
                                                                                                                                                                                                                                                                                href="mailto:kontakt@dinkyrka.se"
                                                                                                                                                                                                                                                                                              className="px-5 py-3 rounded-lg bg-blue-600 text-white font-medium hover:bg-blue-700 shadow"
                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                        Skicka e-post
                                                                                                                                                                                                                                                                                                                                    </a>
                                                                                                                                                                                                                                                                                                                                                <a
                                                                                                                                                                                                                                                                                                                                                              href="/chat"
                                                                                                                                                                                                                                                                                                                                                                            className="px-5 py-3 rounded-lg bg-purple-600 text-white font-medium hover:bg-purple-700 shadow"
                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                      Öppna chatten
                                                                                                                                                                                                                                                                                                                                                                                                                  </a>
                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                    </section>

                                                                                                                                                                                                                                                                                                                                                                                                                                            {/* Vittnesbörd */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                    <section className="mb-10">
                                                                                                                                                                                                                                                                                                                                                                                                                                                              <h2 className="text-2xl font-semibold mb-3 text-center">Vittnesbörd ✝️</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p className="text-center text-gray-700 mb-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Läs och dela med dig av hur Gud har hjälpt och berört dig i ditt liv.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="flex justify-center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <a
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  href="/testimonies"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                className="px-6 py-3 rounded-lg bg-green-600 text-white font-medium hover:bg-green-700 shadow"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Läs Vittnesbörd
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </section>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {/* WesternWall (Bönevägg) */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <section className="mb-10">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <h2 className="text-2xl font-semibold mb-3 text-center">WesternWall 🙏</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p className="text-center text-gray-700 mb-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Här kan du lämna ett bönämne eller be för andra.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="flex justify-center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <a
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      href="/westernwall"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    className="px-6 py-3 rounded-lg bg-yellow-500 text-white font-medium hover:bg-yellow-600 shadow"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Gå till WesternWall
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </section>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {/* Tillbaka-knapp */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
