// Path: app/license/page.tsx
// Vision Framtid – Hybrid License v1.0 (SV/EN sammanfattning)

export default function LicensePage() {
  return (
      <div className="min-h-screen bg-gradient-to-br from-amber-50 via-white to-rose-50">
            <main className="container mx-auto px-4 py-10 prose prose-slate max-w-3xl">
                    <h1>Vision Framtid – Hybrid License v1.0</h1>
                            <p className="text-sm opacity-70">Last updated: 2025-09-22</p>

                                    <h2>🇸🇪 Svenska</h2>
                                            <p>
                                                      Denna kod och data är fri att använda för:
                                                              </p>
                                                                      <ul>
                                                                                <li>Forskning, utbildning, samhällsutveckling</li>
                                                                                          <li>Att bygga hemsidor/appar som sprider information om projekten</li>
                                                                                                    <li>Kombination med egna ideella initiativ för att skapa goodwill</li>
                                                                                                            </ul>
                                                                                                                    <p><strong>Villkor:</strong></p>
                                                                                                                            <ul>
                                                                                                                                      <li>Materialet får inte användas för vinstdrivande exploatering som går emot syftet
                                                                                                                                                  (t.ex. spekulation, bedrägeri, eller att ta betalt av de som projekten är avsedda att hjälpa).</li>
                                                                                                                                                            <li>Projekten ska presenteras som <strong>gratis för Afrikas invånare</strong> där så är avsikten.</li>
                                                                                                                                                                      <li>Attribution krävs: <em>“Source: Vision Framtid – FOR AFRICA, FOR FUTURE!”</em></li>
                                                                                                                                                                              </ul>
                                                                                                                                                                                      <p>
                                                                                                                                                                                                <strong>Kommersiell användning:</strong> om koden/datan används i kommersiellt syfte
                                                                                                                                                                                                          (t.ex. i en betald produkt eller tjänst), krävs en separat licens från Vision Framtid.
                                                                                                                                                                                                                  </p>

                                                                                                                                                                                                                          <h2>🇬🇧 English (Summary)</h2>
                                                                                                                                                                                                                                  <p>
                                                                                                                                                                                                                                            The code and data are free to use for research, education, and social-good websites/apps.  
                                                                                                                                                                                                                                                      <strong>Not allowed:</strong> profit exploitation against the purpose (e.g. charging the intended beneficiaries).  
                                                                                                                                                                                                                                                                <strong>Attribution required:</strong> “Source: Vision Framtid – FOR AFRICA, FOR FUTURE!”
                                                                                                                                                                                                                                                                        </p>
                                                                                                                                                                                                                                                                                <p>
                                                                                                                                                                                                                                                                                          <strong>Commercial use:</strong> requires a separate license from Vision Framtid if used in paid products or services.
                                                                                                                                                                                                                                                                                                  </p>

                                                                                                                                                                                                                                                                                                          <hr />
                                                                                                                                                                                                                                                                                                                  <p>
                                                                                                                                                                                                                                                                                                                            Copyright © {new Date().getFullYear()} Vision Framtid.
                                                                                                                                                                                                                                                                                                                                      All rights reserved where applicable.  
                                                                                                                                                                                                                                                                                                                                                For commercial licensing, contact:&nbsp;
                                                                                                                                                                                                                                                                                                                                                          <a href="mailto:magnus.lulea@proton.me">magnus.lulea@proton.me</a>
                                                                                                                                                                                                                                                                                                                                                                  </p>
                                                                                                                                                                                                                                                                                                                                                                        </main>
                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                              }
