// app/app-room/page.tsx
"use client"

import Link from "next/link"
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card"

import { Heart, Church, Shield, Sparkles, Leaf } from "lucide-react"

export default function AppRoomPage() {
  return (
      <div className="min-h-screen bg-gradient-to-br from-gray-50 via-white to-purple-50">
            <main className="container mx-auto px-4 py-10">
                    {/* Titel */}
                            <h1 className="text-4xl font-bold text-center mb-10">🚪 App-rummet</h1>
                                    <p className="text-center text-gray-600 mb-12">
                                              Utforska och starta dina appar. En central plats för alla projekt.
                                                      </p>

                                                              {/* Grid med appar */}
                                                                      <div className="grid gap-6 md:grid-cols-2">
                                                                                <Link href="/charity">
                                                                                            <Card className="hover:shadow-lg transition cursor-pointer">
                                                                                                          <CardHeader>
                                                                                                                          <CardTitle className="flex items-center gap-2">
                                                                                                                                            <Heart className="h-5 w-5 text-red-500" /> Charity
                                                                                                                                                            </CardTitle>
                                                                                                                                                                          </CardHeader>
                                                                                                                                                                                        <CardContent>
                                                                                                                                                                                                        Ge gåvor och stöd projekt för familjer och barn i nöd.
                                                                                                                                                                                                                      </CardContent>
                                                                                                                                                                                                                                  </Card>
                                                                                                                                                                                                                                            </Link>

                                                                                                                                                                                                                                                      <Link href="/">
                                                                                                                                                                                                                                                                  <Card className="hover:shadow-lg transition cursor-pointer">
                                                                                                                                                                                                                                                                                <CardHeader>
                                                                                                                                                                                                                                                                                                <CardTitle className="flex items-center gap-2">
                                                                                                                                                                                                                                                                                                                  <Leaf className="h-5 w-5 text-green-600" /> Mushroom Maniacs
                                                                                                                                                                                                                                                                                                                                  </CardTitle>
                                                                                                                                                                                                                                                                                                                                                </CardHeader>
                                                                                                                                                                                                                                                                                                                                                              <CardContent>
                                                                                                                                                                                                                                                                                                                                                                              En trygg plats för stöd, gemenskap och psykisk hälsa.
                                                                                                                                                                                                                                                                                                                                                                                            </CardContent>
                                                                                                                                                                                                                                                                                                                                                                                                        </Card>
                                                                                                                                                                                                                                                                                                                                                                                                                  </Link>

                                                                                                                                                                                                                                                                                                                                                                                                                            <Link href="/church">
                                                                                                                                                                                                                                                                                                                                                                                                                                        <Card className="hover:shadow-lg transition cursor-pointer">
                                                                                                                                                                                                                                                                                                                                                                                                                                                      <CardHeader>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <CardTitle className="flex items-center gap-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <Church className="h-5 w-5 text-blue-600" /> Hälso-Kyrkan
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </CardTitle>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </CardHeader>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <CardContent>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Musik, andlighet och AI-samtal om tro.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </CardContent>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </Card>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </Link>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <Link href="/bankid-safe">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <Card className="hover:shadow-lg transition cursor-pointer">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <CardHeader>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <CardTitle className="flex items-center gap-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <Shield className="h-5 w-5 text-gray-700" /> BankID Safe (demo)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </CardTitle>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </CardHeader>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <CardContent>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Testa vår kvantsäkra säkerhetslösning för identitet.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </CardContent>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </Card>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </Link>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <Link href="/vision-framtid">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <Card className="hover:shadow-lg transition cursor-pointer">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <CardHeader>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <CardTitle className="flex items-center gap-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <Sparkles className="h-5 w-5 text-purple-600" /> Vision Framtid
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </CardTitle>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </CardHeader>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <CardContent>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Framtidens prototyper inom AI, energi och hälsa.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </CardContent>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </Card>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {/* Tillbaka-knapp */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="mt-12">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <BackButton fallback="/" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
