// Path: app/privacy/page.tsx
// GDPR-integritetspolicy för Mushroom Maniacs (server component – ingen client-directive)

export default function PrivacyPage() {
  return (
      <div className="min-h-screen bg-gradient-to-br from-gray-50 via-white to-blue-50">
            <main className="container mx-auto px-4 py-10 prose prose-slate max-w-3xl">
                    <h1>Integritetspolicy (GDPR)</h1>
                            <p className="text-sm opacity-70">Senast uppdaterad: 2025-09-22</p>

                                    <p>
                                              Vi värnar om din integritet. Den här policyn beskriver vilken information som behandlas i
                                                        Mushroom Maniacs-appen och på våra sidor, samt dina rättigheter enligt GDPR.
                                                                </p>

                                                                        <h2>Vilka uppgifter behandlas?</h2>
                                                                                <ul>
                                                                                          <li><strong>Kontouppgifter</strong> (om du lämnar dem frivilligt) – t.ex. namn och e-post.</li>
                                                                                                    <li><strong>Kommunikation</strong> – meddelanden du skriver i öppna formulär eller kontaktmail.</li>
                                                                                                              <li><strong>Teknik</strong> – grundläggande loggar (t.ex. felmeddelanden) för att felsöka och förbättra appen. Vi använder ingen tredjeparts-spårning/annonsering.</li>
                                                                                                                        <li><strong>Känsliga uppgifter</strong> – vi efterfrågar inte känsliga personuppgifter. Skriv aldrig akut eller medicinsk information; ring 112 vid fara.</li>
                                                                                                                                </ul>

                                                                                                                                        <h2>Ändamål & rättslig grund</h2>
                                                                                                                                                <ul>
                                                                                                                                                          <li><strong>Driva och förbättra tjänsten</strong> (berättigat intresse).</li>
                                                                                                                                                                    <li><strong>Kommunicera på din begäran</strong> (avtal/samtycke).</li>
                                                                                                                                                                              <li><strong>Följa lagkrav</strong> (rättslig förpliktelse), om tillämpligt.</li>
                                                                                                                                                                                      </ul>

                                                                                                                                                                                              <h2>Lagringstid</h2>
                                                                                                                                                                                                      <p>
                                                                                                                                                                                                                Vi sparar uppgifter bara så länge de behövs för ändamålen ovan eller enligt lag, därefter raderas eller anonymiseras de.
                                                                                                                                                                                                                        </p>

                                                                                                                                                                                                                                <h2>Delning till tredje part</h2>
                                                                                                                                                                                                                                        <p>
                                                                                                                                                                                                                                                  Vi säljer inte dina data. Vid behov kan driftleverantörer (t.ex. hosting) behandla data som personuppgiftsbiträden under avtal och enligt GDPR.
                                                                                                                                                                                                                                                          </p>

                                                                                                                                                                                                                                                                  <h2>Dina rättigheter</h2>
                                                                                                                                                                                                                                                                          <ul>
                                                                                                                                                                                                                                                                                    <li>Rätt till tillgång (registerutdrag)</li>
                                                                                                                                                                                                                                                                                              <li>Rättelse och radering</li>
                                                                                                                                                                                                                                                                                                        <li>Dataportabilitet och begränsning av behandling</li>
                                                                                                                                                                                                                                                                                                                  <li>Invändning mot behandling</li>
                                                                                                                                                                                                                                                                                                                            <li>Återkalla samtycke (om samtycke använts)</li>
                                                                                                                                                                                                                                                                                                                                      <li>Klagomål till IMY (Integritetsskyddsmyndigheten) i Sverige</li>
                                                                                                                                                                                                                                                                                                                                              </ul>

                                                                                                                                                                                                                                                                                                                                                      <h2>Cookies</h2>
                                                                                                                                                                                                                                                                                                                                                              <p>
                                                                                                                                                                                                                                                                                                                                                                        Vi använder i utgångsläget endast nödvändiga cookies (t.ex. session/funktion). Ingen tredjeparts-reklam eller cross-site spårning.
                                                                                                                                                                                                                                                                                                                                                                                </p>

                                                                                                                                                                                                                                                                                                                                                                                        <h2>Kontakt</h2>
                                                                                                                                                                                                                                                                                                                                                                                                <p>
                                                                                                                                                                                                                                                                                                                                                                                                          Personuppgiftsansvarig: <strong>Mushroom Maniacs</strong><br />
                                                                                                                                                                                                                                                                                                                                                                                                                    E-post: <a href="mailto:magnus.lulea@proton.me">magnus.lulea@proton.me</a><br />
                                                                                                                                                                                                                                                                                                                                                                                                                              Tel: <a href="tel:+46728502584">+46 72-850 25 84</a>
                                                                                                                                                                                                                                                                                                                                                                                                                                      </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                              <h2>Ändringar i policyn</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                      <p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                Policyn kan uppdateras. Ny version publiceras här med nytt datum för “Senast uppdaterad”.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
