// app/westernwall/page.tsx
"use client"

import { useEffect, useState } from "react"
import  BackButton  from "@/components/BackButton"

type Prayer = {
  id: string
    name: string
      text: string
        amens: number
          createdAt: number
          }

          const STORAGE_KEY = "westernwall_prayers_v1"

          export default function WesternWallPage() {
            const [name, setName] = useState("")
              const [text, setText] = useState("")
                const [prayers, setPrayers] = useState<Prayer[]>([])

                  // Load from localStorage on mount
                    useEffect(() => {
                        try {
                              const raw = localStorage.getItem(STORAGE_KEY)
                                    if (raw) setPrayers(JSON.parse(raw))
                                        } catch {}
                                          }, [])

                                            // Persist on change
                                              useEffect(() => {
                                                  try {
                                                        localStorage.setItem(STORAGE_KEY, JSON.stringify(prayers))
                                                            } catch {}
                                                              }, [prayers])

                                                                function addPrayer(e: React.FormEvent) {
                                                                    e.preventDefault()
                                                                        const trimmed = text.trim()
                                                                            if (!trimmed) return
                                                                                const p: Prayer = {
                                                                                      id: crypto.randomUUID(),
                                                                                            name: name.trim() || "Anonym",
                                                                                                  text: trimmed,
                                                                                                        amens: 0,
                                                                                                              createdAt: Date.now(),
                                                                                                                  }
                                                                                                                      setPrayers([p, ...prayers])
                                                                                                                          setText("")
                                                                                                                            }

                                                                                                                              function amen(id: string) {
                                                                                                                                  setPrayers(prev =>
                                                                                                                                        prev.map(p => (p.id === id ? { ...p, amens: p.amens + 1 } : p))
                                                                                                                                            )
                                                                                                                                              }

                                                                                                                                                function clearAll() {
                                                                                                                                                    if (confirm("Rensa alla bönämnen på denna enhet?")) {
                                                                                                                                                          setPrayers([])
                                                                                                                                                              }
                                                                                                                                                                }

                                                                                                                                                                  return (
                                                                                                                                                                      <main className="min-h-screen bg-gradient-to-br from-white via-blue-50 to-purple-50">
                                                                                                                                                                            <div className="container mx-auto max-w-3xl px-4 py-10">
                                                                                                                                                                                    <h1 className="text-4xl font-bold mb-2 text-center">WesternWall 🙏</h1>
                                                                                                                                                                                            <p className="text-center text-gray-700 mb-8">
                                                                                                                                                                                                      Lämna ett bönämne eller be för andra. (Sparas lokalt på din enhet.)
                                                                                                                                                                                                              </p>

                                                                                                                                                                                                                      {/* Form */}
                                                                                                                                                                                                                              <form
                                                                                                                                                                                                                                        onSubmit={addPrayer}
                                                                                                                                                                                                                                                  className="bg-white border rounded-xl shadow p-4 mb-8"
                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                    <div className="grid gap-3">
                                                                                                                                                                                                                                                                                <input
                                                                                                                                                                                                                                                                                              value={name}
                                                                                                                                                                                                                                                                                                            onChange={e => setName(e.target.value)}
                                                                                                                                                                                                                                                                                                                          placeholder="Ditt namn (valfritt)"
                                                                                                                                                                                                                                                                                                                                        className="border rounded-md px-3 py-2"
                                                                                                                                                                                                                                                                                                                                                    />
                                                                                                                                                                                                                                                                                                                                                                <textarea
                                                                                                                                                                                                                                                                                                                                                                              value={text}
                                                                                                                                                                                                                                                                                                                                                                                            onChange={e => setText(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                          placeholder="Skriv ditt bönämne…"
                                                                                                                                                                                                                                                                                                                                                                                                                        rows={4}
                                                                                                                                                                                                                                                                                                                                                                                                                                      className="border rounded-md px-3 py-2"
                                                                                                                                                                                                                                                                                                                                                                                                                                                  />
                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="flex items-center gap-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            type="submit"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            className="rounded-lg bg-blue-600 hover:bg-blue-700 text-white font-medium px-4 py-2"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Lägg till bön
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      type="button"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      onClick={clearAll}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      className="rounded-lg bg-gray-200 hover:bg-gray-300 text-gray-800 px-4 py-2"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      title="Rensar lokala bönämnen på denna enhet"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Rensa lokalt
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </form>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {/* List */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="grid gap-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {prayers.length === 0 ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="text-center text-gray-600">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Inga bönämnen ännu. Var först att skriva ett 🙏
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      prayers.map(p => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <article
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    key={p.id}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    className="bg-white border rounded-xl shadow p-4"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="flex items-center justify-between mb-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="font-semibold">{p.name}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <time className="text-sm text-gray-500">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {new Date(p.createdAt).toLocaleString("sv-SE")}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </time>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p className="text-gray-800 mb-3 whitespace-pre-wrap">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {p.text}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                onClick={() => amen(p.id)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  className="rounded-lg bg-yellow-500 hover:bg-yellow-600 text-white font-medium px-3 py-1"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Amen ({p.amens})
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </article>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {/* Back */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <BackButton fallback="/church" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
